### ISSUE TITLE
Adding to Modes for iOS?

### ISSUE THREAD

**Issue by boourns** [damonholzborn/WithW#1]
Hi @damonholzborn,

Do you mind if I add this to https://github.com/boourns/synthmodes?  I will likely rework it a bit to fit the format, and would link back to the website and project with your credit as author.

I see the license is MIT but wanted to reach out anyways.

If you want to try out the ios app send me an email tom@burns.ca and I'll send you a promo code.

Cheers,
Tom

**Comment by damonholzborn** [comment]
Sure, go for it! As you say, the MIT license allows whatever, but it's nice of you to let me know. Unfortunately, since it's just a big pile of HTML, you'll probably be starting from scratch with the formatting, but at least the copy should give you a good head start.

Thanks for the offer of a promo code, I'll send you an email.
